version: '3.1'
services:
  mongo:
    image: mongo:latest
    container_name: mongo
    env_file:
      - ./.env
    volumes:
      - local-mongo:/data/db
    ports:
      - '27017:27017'

volumes:
  local-mongo:
